
cache:
  paths:
  - node_modules/

before_script:
  - npm i -g grunt
  - npm i

stages:
  - build
  - test

build_async:
  stage: build
  script:
   - grunt build

test_async:
  stage: test
  script:
   - grunt test
  tags:
    - docker
